import { Poppins } from "next/font/google";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css"
import "bootstrap-icons/font/bootstrap-icons.css"
import Navigation from "@/components/Navigation";
import { AOSInit } from "@/components/AOS";
import Footer from "@/components/Footer";

const poppins = Poppins({ subsets: ["latin"], weight: ["100", "200", "300"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body className={`index-page ${poppins.className}`}>
        <AOSInit />
        <Navigation />

        {children}
        <Footer />

      </body>
    </html>
  );
}
